### ISSUE TITLE
Update interface for newer CoolProp version 6.1.X

### ISSUE THREAD

**Issue by slamer59** [modelica/ExternalMedia#3]
Hello,
the wrapper with [ExternalMedia ](
https://github.com/modelica/ExternalMedia) is not maintained anymore here since 3 years.

The wrapper seemed to be in sync with version 4.2.x of coolprop. 

There is precompiled librarie for windows but I was not able to compile it directly from source. Some simple update have to be made in this libraries. Maybe it is a good idea to update it ? Integrate it with CoolProp ? 

I will open the same issue in [CoolProp](https://github.com/CoolProp/CoolProp/issues/1572).

The work will be : 
-> make to CMake (easier to make cross compilation)
-> change functions from v4.X to 6.X

What do you think ?
I may take some times to make this change with some helps.

Thomas

**Comment by bilderbuchi** [comment]
See https://github.com/CoolProp/ExternalMedia/issues/13#issuecomment-334721942 and following for an update of the situation.

**Comment by jowr** [comment]
You have seen this repository, right? https://github.com/CoolProp/ExternalMedia

**Comment by slamer59** [comment]
After bilderbuchi comment I saw that. Thanks for the update. I will follow comments on this topic.

**Comment by thorade** [comment]
Also see the summary in the wiki:
https://github.com/modelica/ExternalMedia/wiki

**Comment by casella** [comment]
OK, I apologize for the lazy management, trying to figure out how to deal with this project properly was not trivial, due to multiple conflicting requirements. 

I had some ideas how to proceed that I wrote in the wiki in October, but after prototyping work and some discussion with @adrpo I have changed my mind a bit. 

I tried to summarize the situation and requirement and to come up with a detailed action plan in issue #4, please comment there

**Comment by casella** [comment]
The discussion continues in #4
